### ISSUE TITLE
Ayudark text colour

### ISSUE THREAD

**Issue by RabidWolf** [maboroshin/qBittorrentDarktheme#10]
I'm using ayudark (rev 3) and all the text colours are grey ie error, downloading and seeding instead of red (error), green (downloading) and whatever colour seeding is meant to be. is it meant to be like that?

Apart from that, great themes. 👍

**Comment by maboroshin** [comment]
I have a feeling it's not a bug. It is reported in the "issue for 4.2.2". I feel like the newly implemented specification method is invalid. Therefore, I don't know how to specify it.

Maybe, The default values of orange and green seem to be reflected in some cases. jagannatharjun's Darkstylesheet.qbtheme is so. Mumble-Dark.qbtheme is not. But it's not easy to replicate.

If I have the time, I will continue this investigation.

**Comment by RabidWolf** [comment]
> I have a feeling it's not a bug. It is reported in the "issue for 4.2.2". I feel like the newly implemented specification method is invalid. Therefore, I don't know how to specify it.
> 
> Maybe, The default values of orange and green seem to be reflected in some cases. jagannatharjun's Darkstylesheet.qbtheme is so. Mumble-Dark.qbtheme is not. But it's not easy to replicate.
> 
> If I have the time, I will continue this investigation.

jagannatharjun has just released an updated version of Mumble-Dark with the colours so might be worth seeing what changes he/she made.

**Comment by maboroshin** [comment]
It may be possible. It's not easy.

**Comment by maboroshin** [comment]
Success. Please try a new release.

**Comment by RabidWolf** [comment]
Works great thanks.
