### ISSUE TITLE
Checkboxes are covered with the text in "Select Graphs" menu

### ISSUE THREAD

**Issue by adem4ik** [maboroshin/qBittorrentDarktheme#12]
qb: v4.2.5 x64
OS: Windows 10 x64

1) Open Speed tab at the bottom of the transfer list
2) Click on "Select Graphs" menu

**Result:** checkboxes are covered with the text 
![image](https://user-images.githubusercontent.com/4707112/80316762-b245e200-8810-11ea-9cb7-09d707434913.png)
**Expected result:** checkboxes aren't covered with the text:
- original theme
![image](https://user-images.githubusercontent.com/4707112/80316799-e7eacb00-8810-11ea-9112-ddd48ccb040d.png)
- jagannatharjun's [darkstylesheet.qbtheme](https://github.com/jagannatharjun/qbt-theme)
![image](https://user-images.githubusercontent.com/4707112/80316826-1bc5f080-8811-11ea-8a2d-e55cb1d9cf84.png)

**Additional info:** I think it might be working correctly in jagannatharjun's theme cause there is another issue the menus, which was fixed in maboroshin's themes:
- jagannatharjun's theme
![image](https://user-images.githubusercontent.com/4707112/80316959-ec63b380-8811-11ea-8771-c8655711890f.png)
- maboroshin's theme
![image](https://user-images.githubusercontent.com/4707112/80316936-d0f8a880-8811-11ea-999d-f5a87af18b44.png)

**Comment by maboroshin** [comment]
Thank you for the report. At a later date, I will try the adjustment.

The menu icon, however, may be a trade-off. As you say. If one is good, the other is bad.
