### ISSUE TITLE
Solarized is identical to ICEBERG

### ISSUE THREAD

**Issue by Exablade** [maboroshin/qBittorrentDarktheme#14]
The last version of the Solarized theme is identical to ICEBERG, and they have the same checksums. The previous version works as expected, so I guess it's just a copypaste error.

**Comment by maboroshin** [comment]
Sorry, It seems to miss. The procedure is complex and easy to miss. I'll re-upload it in the near future.

**Comment by maboroshin** [comment]
@Exablade : I re-uploaded.👍
