### ISSUE TITLE
"Execution Log" is unreadable.

### ISSUE THREAD

**Issue by Lifell** [maboroshin/qBittorrentDarktheme#15]
The "Execution Log" tab is unreadable on the "ayuDark.qbtheme" theme because of the text having almost the exact same color as the background.

**Comment by maboroshin** [comment]
Sorry. I'll investigate when I have time.

**Comment by Lifell** [comment]
No need to be sorry. Thanks a lot for the skin/theme!

**Comment by maboroshin** [comment]
Hi! I fixed log color.
Please try new release psychedelic experience.😁

**Comment by Lifell** [comment]
It's readable now! Thanks a lot for the fix.:smile::+1:
