### ISSUE TITLE
Issue qBitorrent v4.3.0

### ISSUE THREAD

**Issue by Bastien42** [maboroshin/qBittorrentDarktheme#16]
Stalled torrent are way to dark with this new version of qBitorrent 

![Capture d’écran 2020-10-19 030828](https://user-images.githubusercontent.com/37946663/96391260-69b42380-11b8-11eb-913d-322d0cf41cc5.png)

tested with all themes pictures using ICEBERG

**Comment by Bastien42** [comment]
just saw that completed torrent have the same issue as they were greyish before now they appear as very dark blue almost unreadable

**Comment by Bastien42** [comment]
![Capture d’écran 2020-10-19 031455](https://user-images.githubusercontent.com/37946663/96391515-46d63f00-11b9-11eb-84d3-121a3e9a5f65.png)

**Comment by nevven** [comment]
It is because: qBittorrent v4.3.0 was released

> Theming support has been enhanced but previous theme bundles will not work properly with this release. Please contact the theme provider for a fix. 

Hopefully fix will come soon

**Comment by Bastien42** [comment]
> It is because: qBittorrent v4.3.0 was released
> 
> > Theming support has been enhanced but previous theme bundles will not work properly with this release. Please contact the theme provider for a fix.
> 
> Hopefully fix will come soon

Yes i figured that's why I up this so that they are aware of that as they may not use the latest qbitorrent version

**Comment by Sleepybear** [comment]
+1 this, just got a new Rig and installed Qbt fresh, and theme is not working at all.

**Comment by Sleepybear** [comment]
@Bastien42 I fixed the theme files and did a PR, but you can download them from my fork and the Sleepybear-patch-1 branch: https://github.com/Sleepybear/qBittorrentDarktheme/tree/Sleepybear-patch-1

**Comment by DSGriff** [comment]
@Bastien42 It'd be great if you could fix the downloading icon too, it's still in black. Thanks for your work!

**Comment by Sleepybear** [comment]
I updated my PR to have Grey icons for the stalled UP/DL

**Comment by brian6932** [comment]
> @Bastien42 I fixed the theme files and did a PR, but you can download them from my fork and the Sleepybear-patch-1 branch: https://github.com/Sleepybear/qBittorrentDarktheme/tree/Sleepybear-patch-1

Thank you

**Comment by maboroshin** [comment]
Thank you for your help. I'll check when I have time.
