### ISSUE TITLE
Theme does not change on elementary OS

### ISSUE THREAD

**Issue by nandgator** [maboroshin/qBittorrentDarktheme#20]
I've set the theme like this:

![image](https://user-images.githubusercontent.com/38415384/103187517-94260980-48ea-11eb-8f2f-77d6824c3c66.png)

But it remains in the light theme. How do I solve this, please?

**System**: elementary OS 5.1.7
**qbittorrent**: v4.3.2

**Comment by maboroshin** [comment]
@joe733 If you use [jagannatharjun's theme](https://github.com/jagannatharjun) and it stays bright, then it's not a theme problem.

**Comment by nandgator** [comment]
![Screenshot from 2020-12-30 00-00-03](https://user-images.githubusercontent.com/38415384/103305784-0b19ea00-4a32-11eb-8216-f4d4579b11c4.png)

Nope 😕. Only the `Preference` titlebar changes (even after restart). And the same goes for he following themes:

![image](https://user-images.githubusercontent.com/38415384/103306013-8f6c6d00-4a32-11eb-8403-4d6023233031.png)

Any system settings should I tweak?

**Comment by nandgator** [comment]
@maboroshin I've an issue here: https://github.com/jagannatharjun/qbt-theme/issues/43

**Comment by jagannatharjun** [comment]
qBitTorrent issue https://github.com/qbittorrent/qBittorrent/issues/13410
