### ISSUE TITLE
Need 4.3.6 Update

### ISSUE THREAD

**Issue by jupiter104** [maboroshin/qBittorrentDarktheme#25]
Hi. your themes are the best. I especially like the iceberg one. Unfortunately, with the latest stable version of qBittorrent 4.3.6, if I use the 4.3.0 Rev10 theme, the title bar remains white. It doesn't switch to dark mode even if Windows is in dark mode. Apart from that, the rest of the theme looks fine. So, I think to update the theme for the latest stable version, you just have to make that minor change of the title bar.

**Comment by maboroshin** [comment]
Same issue: https://github.com/maboroshin/qBittorrentDarktheme/issues/19
