### ISSUE TITLE
[ayuDark] Please make changes to "pieces" color.

### ISSUE THREAD

**Issue by fourteen-1** [maboroshin/qBittorrentDarktheme#26]
![qbittorrent_43alVWA548DARK](https://user-images.githubusercontent.com/73333396/128327284-b172520b-8fa2-41ac-af65-d12700cd2a89.png)

Please change "Missing pieces" color to red, and "complete pieces" color to blue.

![qbittorrent_MO0WXRtrOq](https://user-images.githubusercontent.com/73333396/128327296-54ff7d74-ff5e-45d4-b00f-8ae536940487.png)

Please change "Unavailable pieces" color to red, and "available pieces" color to blue.

![qbittorrent_VnoSr6n42BDARK](https://user-images.githubusercontent.com/73333396/128327750-305b4d52-ed51-427f-86d6-da865caf3780.png)

Please make changes to the shade of all colors as they are a bit hard to see. (Blue and green almost blends together and is barely legible).

Optional: I don't know if it was a design decision, but there is a blue outline on just the top and left sides of the progress bar, it kind of looks out of place imo. Makes changes to it as you see fit, or don't. Up to the dev(s).

Thank you. :))

**Comment by maboroshin** [comment]
Anyway, the specifications are not public, and most people can't create a theme. I'm repeating trial and error. The result is the current theme. In my experiment, The color of the tooltip in the image does not change. However, the color of the bar can be changed.

"Partial pieces" is fixed at green color in the program code. So, If it's not a bright blue, it's hard to distinguish from green. But it's a dark theme. Dark blue and dark green will be hard to distinguish. So, It needed "Complete" to be a slightly darker purple (reddish blue).

"Missing/Unavailable" should remain black. This is using the color assignment "Base", which should not be assigned Red color. There is no problem in assigning it now, but theoretically it should not be assigned. Also, the absence of color is more appropriate for the "Missing".

The lines on the top and left are frame/border. It is not my theme, but the developer's program code. It can change the color. But, Without the frame, the width of 100% is unknown. So, frame is considered necessary.
