### ISSUE TITLE
Progress Bar Text too large

### ISSUE THREAD

**Issue by Shuggaloaf** [maboroshin/qBittorrentDarktheme#30]
I believe this problem *probably* only affects high DPI displays. As you can see the text is cut off. 

![image](https://user-images.githubusercontent.com/79543184/145486144-866e1458-1b44-4270-a92e-ab5d360a2f72.png)

All other text looks fine. Even the very small text in the search bar looks fine. 

Since this is probably specific to those of us using 4K / High DPI screens, is there a work-around for us? Maybe a way to set the progress bar text to a smaller size?

**Comment by maboroshin** [comment]
See also: https://github.com/maboroshin/qBittorrentDarktheme/issues/24

**Comment by Shuggaloaf** [comment]
> See also: #24

Interesting. The only text affected for me is those progress bars. Maybe theme specific?

edit: Also, to be clear, this does NOT happen in qBittorrent _without_ this theme installed.

**Comment by maboroshin** [comment]
I see!

I don't know how to fix it.

**Comment by Shuggaloaf** [comment]
>I don't know how to fix it. 

Is there a specific line of code that affects the size of the progress bars (or _lines_, or the variable name)? I'd be happy to play around and do some testing on my end if you wouldn't mind pointing me in the right direction.

**Comment by Splike** [comment]
You can find the css source in the `.qss` file.

Search for `QProgressBar` to find the section that has to do with the progress bar. Hopefully that'll get you started looking for a fix.

**Comment by Shuggaloaf** [comment]
Thanks, I'll take a look! If I find anything I'll post back. For now I'll go ahead and close this one.
