### ISSUE TITLE
Percentage Bar still isn't alligned even with the latest version

### ISSUE THREAD

**Issue by GitExploraa** [maboroshin/qBittorrentDarktheme#32]
running qbittorrent 4.4.1 with the latest version of the Theme, and as the screenshot bellow shows the text on the progressbar isnt well centered, dunno if this is a bug with qbitorrent itself (all the themes i tried gave me this) or with the themes themselves (this one included)
![image](https://user-images.githubusercontent.com/44654056/157500354-0f00028b-6295-42e3-8642-eab262741936.png)

**Comment by maboroshin** [comment]
Is it a high DPI monitor?
Same problem reported and not resolved : https://github.com/maboroshin/qBittorrentDarktheme/issues/30

I am not using a high DPI monitor, so I cannot adjust. And I do not know adjustable it.

**Comment by GitExploraa** [comment]
hey, so after some more digging, it turns out that the app does this where there's a custom text size set in windows, so the text gets bigger but other UI elements dont follow, thus it looks like this, hope this helps with fixing the issue

**Comment by WhinVader** [comment]
<details> 
 <summary>Example</summary>
 ``` 
long console output here 
``` 
</details>
