### ISSUE TITLE
some context menu items (text) are not aligned

### ISSUE THREAD

**Issue by b-user** [maboroshin/qBittorrentDarktheme#37]
right-click on the torrent that has not been downloaded yet

![Absinthe-1](https://user-images.githubusercontent.com/11581901/210227606-2c65f5b9-568c-4011-ae3b-c0dfa0cf37c2.png)

**Comment by maboroshin** [comment]
Perhaps the problem is not caused by a theme : https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591917158
