### ISSUE TITLE
Status, Categories etc. need scrolling unlike the default scheme.

### ISSUE THREAD

**Issue by stephen147** [maboroshin/qBittorrentDarktheme#4]
In the default scheme all the top 3 items, status, categories and tags show without the need for scrolling each of them.

Theme tested here: ayuDark.qbtheme

### Issue with theme
![qSHuYnCAjG](https://user-images.githubusercontent.com/14054664/77483559-5a3a4b00-6e20-11ea-8a77-855781ea334a.png)

### Default theme. They're all in the same view as shown here:
![Ax9m5o1MlE](https://user-images.githubusercontent.com/14054664/77483564-5c9ca500-6e20-11ea-89a4-50250646fc47.png)

**Comment by maboroshin** [comment]
Thank you. I will try it.

Behaver when the left sidebar is long.
* Default: single scrollbar
* These dark theme: each becomes narrower. And no scroll bar.

**Comment by maboroshin** [comment]
Behaver when the left sidebar is long.
* Default: single scrollbar
* Dark themes: each becomes narrower. There is no scroll bar.

**Comment by stephen147** [comment]
It is fixable? Thanks.

**Comment by maboroshin** [comment]
Still unknown. The default is to do this behaver, thus it is possible.

**Comment by maboroshin** [comment]
I could have fixed it!

**Comment by stephen147** [comment]
Indeed you have. Thanks very much.

I didn't get a notification to my email about the updates. Is that something you have to enable?

**Comment by maboroshin** [comment]
Maybe, Update notifications need to be released.
I didn't release it, I simply updated the file.

Delete this:
```
QAbstractScrollArea {
  min-height: 1.25em;
}
```
