### ISSUE TITLE
Context menu empty squares and borderless confusion

### ISSUE THREAD

**Issue by DanGM96** [maboroshin/qBittorrentDarktheme#6]
1. _Automatic Torrent Management_, _Download in sequential order_, _Download first and last pieces first_, _Super seeding mode_ (not in pictures) all have empty spaces on the vanilla theme, but have this weird **squares** on the custom themes. Weirdly, _Queue_ does not share the same problem.

2. The context menus missing borders (or different color borders) blend into the content and makes it look weird. I recommend using the same border colors as used on the tooltips when you hover over the top icons.

Sorry for all the screenshots, I wanted to make sure the problem persists on all themes.
![image](https://user-images.githubusercontent.com/36743739/77723634-c4ddb900-6fcf-11ea-8239-8f2e3a71ca27.png) ![image](https://user-images.githubusercontent.com/36743739/77723511-6c0e2080-6fcf-11ea-9de1-e35e0637e15f.png)
![image](https://user-images.githubusercontent.com/36743739/77723544-8811c200-6fcf-11ea-846d-7079d84149fe.png) ![image](https://user-images.githubusercontent.com/36743739/77723575-a081dc80-6fcf-11ea-85ee-46e8e79cc060.png)

**Comment by adem4ik** [comment]
1) Btw it seems like _Automatic Torrent Management, Download in sequential order, Download first and last pieces first, Super seeding mode_ use different font in compare with original theme:
![image](https://user-images.githubusercontent.com/4707112/77821418-92cd7380-7103-11ea-9c5f-dbf98389f6d3.png)
![image](https://user-images.githubusercontent.com/4707112/77821392-5d288a80-7103-11ea-95c7-a1f02b01178e.png)

**Comment by maboroshin** [comment]
1. This is not a theme's issue. I was the first to report on this issue.
2. I'm aware of that problem. But I released it first. It was quickness rather than perfection. I released additional border version, now.
