### ISSUE TITLE
need to get rid of the gradients

### ISSUE THREAD

**Issue by PhilBaz** [maboroshin/qBittorrentDarktheme#7]
Sweet dude....Very close, just need to get rid of the janky gradients on the lower buttons. Then it will be perfect! Gradients on the interface is a bit outdated and don't look good. Take them off and you will have the best theme by far :)

**Comment by maboroshin** [comment]
The icons were hard to see by trial and error. 
![image](https://user-images.githubusercontent.com/41102508/77849880-d7dbcd80-7209-11ea-9e07-24d86d1f51d0.png) :Sample image

That's where the gradient was born. Back to mono color again. I released it.

**Comment by PhilBaz** [comment]
Awesome!!! Looks great!
