### ISSUE TITLE
White background in Gnome

### ISSUE THREAD

**Issue by maboroshin** [maboroshin/qBittorrentDarktheme#8]
@charmesal reported in https://github.com/maboroshin/qBittorrentDarktheme/issues/3:
> I'm also having color issues but nothing like you have described already. Some text is still dark and the background of some fields are still white. This could be an issue with Gnome but I am unable to find anything about this yet. I'm still a beginner when it comes to programming but I might be able to help with testing.
> ![Screenshot from 2020-04-02 00-27-14](https://user-images.githubusercontent.com/13157582/78192827-3d81c100-7479-11ea-82e2-b3b3ffe3e309.png)

**Comment by maboroshin** [comment]
@charmesal Can you try [test.qbtheme](https://github.com/maboroshin/qBittorrentDarktheme/blob/master/test/test.qbtheme)?

`QDialog`'s `background` can be set.  On Windows, it's dark without this value. This value were also reflected in Windows.

If you have any other issues, please post the images here.

**Comment by charmesal** [comment]
I have tried test.qbtheme and sadly the issue remains. I will see if I can get a different distro with Gnome up in a VM to test whether this is a Manjaro, or Gnome issue

**Comment by maboroshin** [comment]
It's also difficult because it could be an OS issue or a Qt issue. This setting has been reflected in Windows. This is included in the test.qbtheme above.

```
QDialog { /* for Gnome about Dialog : background */
  background-color: #000000;
}
```

**Comment by maboroshin** [comment]
Related:https://github.com/qbittorrent/qBittorrent/issues/13410 : .qbttheme doesn't work across different Qt versions.

**Comment by jagannatharjun** [comment]
qbittorrent/qBittorrent#13410 references qbttheme as a container that is not cross-platform but if style loads (you can check in the log) all the stylesheet-related changes should apply correctly.
